config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "dashboard#index"

  resources :locations
  resources :users, only: [:index]
  get ':username', to: 'users#show', as: :user_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  validates :location_name, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  # validates :is_private, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :display_name, presence: true
  validates :username, presence: true, :format => { :with => /[^.]*/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:display_name, :username, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:display_name, :username, :email, :password, :current_password)}
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @locations = Location.where("user_id = :user_id", user_id: current_user.id)
    @shared_locations = Location.where("shared_with @> '{\"data\": [:user_id]}'", user_id: current_user.id)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.where("user_id = :user_id", user_id: current_user.id)
    @shared_locations = Location.where("shared_with @> '{\"data\": [:user_id]}'", user_id: current_user.id)
  end
  
  def new
    @location = Location.new
    @users = User.where("id != :current_user", current_user: current_user.id)
  end

  def create
    new_data = {}
    new_data[:shared_with] = { data: params[:location][:shared_with].reject {|friend| friend.empty? }.map {|friend_id| friend_id.to_i } }
    new_data[:latitude] = params[:location][:latitude].present? ? params[:location][:latitude].to_f : nil
    new_data[:longitude] = params[:location][:longitude].present? ? params[:location][:longitude].to_f : nil
    new_data[:is_private] = params[:location][:is_private] == "true" ? true : false
    new_data[:location_name] = params[:location][:location_name]
    new_data[:user_id] = current_user.id
    @location = Location.new(new_data)
    if @location.save
      redirect_to locations_path, :notice => "Your location has been shared"
    else
      flash[:alert] = "Something not quite right with your input"
      @users = User.where("id != :current_user", current_user: current_user.id)
      render :new
    end
  end

  def update
  end

  def destroy
  end

  private
  def location_params
    params.require(:location).permit(:location_name, :latitude, :longitude, :shared_with, :is_private)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where("id != :current_user", current_user: current_user.id )
  end

  def show
    @user = User.find_by_username(params[:username])
    @current_user_location = Location.where(user_id: @user.id, is_private: false)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<%= render('layouts/navbar') %>
<div class="container-fluid">
  <div class="col-md-12 p-3">
    <div class="row">
      <h1>Welcome, <%= current_user.display_name %> </h1>
    </div>
    <div class="row mt-3">
      <div id="locationData" data-locations="<%= @locations.to_json %>"></div>
      <div id="sharedLocationData" data-locations="<%= @shared_locations.to_json %>"></div>
      <div id="dashboardMap" class="showMap ml-0"></div>
      <%= javascript_pack_tag "showDashboardMap" %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">PSS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Locations", locations_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, :class => "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "Log Out", destroy_user_session_path, :method => :delete, :class => "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlaceSharingSite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice.present? %>
      <div class="alert alert-info notice  alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger  alert-dismissible fade show" role ="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<%= render('layouts/navbar') %>
<div class="container-fluid">
  <div class="col-md-12 p-3">
    <div class="row">
      <h1>Location Index</h1>
      <%= link_to "Add New Location", new_location_path, {class: "btn btn-lg btn-primary ml-auto"} %>
    </div>
    <div class="row mt-3">
      <div id="locationData" data-locations="<%= @locations.to_json %>"></div>
      <div id="sharedLocationData" data-locations="<%= @shared_locations.to_json %>"></div>
      <div id="dashboardMap" class="showMap ml-0"></div>
      <%= javascript_pack_tag "showDashboardMap" %>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<%= render('layouts/navbar') %>
<%= form_with model: @location do |form| %>
  <div class="container-fluid">
    <div class="col-md-12 p-3">
      <div class="row">
        <h1>Share your places</h1>
      </div>
      <div class="row">
          <div class="col-md-6">
              <div class="form-group">
                <%= form.label :location_name %>
                <%= form.text_field :location_name, { class: "form-control" } %>
                <% @location.errors.full_messages_for(:location_name).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>
              <div class="form-group">
                <%= form.label :is_private, "Public Share" %>
                <%= form.radio_button :is_private, false %>
                <%= form.label :is_private, "Yes" %>
                <%= form.radio_button :is_private, true %>
                <%= form.label :is_private, "No" %>
              </div>
              <div class="form-group">
                <%= form.label :shared_with, "Shared with" %>
                <%= form.select :shared_with, @users.map {|user| [user.display_name, user.id]}, {  }, { class: "form-control", multiple: true } %>
              </div>
              <div class="form-group">
                <%= form.submit "Share my location", { class: "btn btn-md btn-primary" } %>
              </div>
          </div>
          <div class="col-md-6">
              <% errors = [] %>
              <% @location.errors.full_messages_for(:latitude).each do |message| %>
                <% errors.push(message) %>
              <% end %>
              <% @location.errors.full_messages_for(:longitude).each do |message| %>
                <% errors.push(message) %>
              <% end %>
              <%= form.hidden_field :latitude %>
              <%= form.hidden_field :longitude %>
              <%= form.label :latitude, "Please click on the map to pinpoint your location" %>
              <div id="locationMap" class="inputMap"></div>
              <%= javascript_pack_tag "openLayers" %>
              <div><%= errors.join(", ") %></div>
          </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<%= render('layouts/navbar') %>
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Display Name</th>
      <th>Email</th>
      <th>Public Locations</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.display_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to "Show", user_profile_path(username: user.username) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<%= render('layouts/navbar') %>
<div class="container-fluid">
  <div class="col-md-12 p-3">
    <div class="row">
      <h1>This is <%= @user.display_name %> public locations</h1>
    </div>
    <div class="row">
      <div id="currentUserLocation" data-locations="<%= @current_user_location.to_json %>"></div>
      <div id="currentUserPlaces" class="showMap ml-0"></div>
      <%= javascript_pack_tag "showLocationProfile" %>
    </div>
  </div>
</div>